/**
 * Generate GitHub Actions workflow templates
 */

/**
 * Get package manager setup action
 */
function getPackageManagerSetup(packageManager) {
    switch (packageManager) {
        case 'pnpm':
            return `      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
`;
        case 'yarn':
            return ''; // Yarn is supported by default in setup-node
        case 'bun':
            return `      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
`;
        default:
            return '';
    }
}

/**
 * Get install command for package manager
 */
function getInstallCommand(packageManager) {
    switch (packageManager) {
        case 'npm':
            return 'npm ci';
        case 'pnpm':
            return 'pnpm install --frozen-lockfile';
        case 'yarn':
            return 'yarn install --frozen-lockfile';
        case 'bun':
            return 'bun install';
        default:
            return 'npm ci';
    }
}

/**
 * Get cache value for package manager
 */
function getCacheValue(packageManager) {
    if (packageManager === 'npm') {
        return '';
    }
    return `          cache: '${packageManager}'`;
}

/**
 * Generate main deployment workflow
 */
function generateMainWorkflow(projectId, apiUrl, packageManager, buildCmd) {
    const pmSetup = getPackageManagerSetup(packageManager);
    const installCmd = getInstallCommand(packageManager);
    const cache = getCacheValue(packageManager);
    const runCmd = packageManager === 'npm' ? `npm run ${buildCmd}` : `${packageManager} run ${buildCmd}`;

    return `# Auto-generated by Scry Storybook Deployer
# Deploy Storybook to production on push to main branch

name: Deploy Storybook

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

${pmSetup}      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
${cache}

      - name: Install dependencies
        run: ${installCmd}

      - name: Build Storybook
        run: ${runCmd}

      - name: Deploy to Scry
        run: npx @scry/storybook-deployer --dir ./storybook-static
        env:
          STORYBOOK_DEPLOYER_API_URL: \${{ vars.SCRY_API_URL }}
          STORYBOOK_DEPLOYER_PROJECT: \${{ vars.SCRY_PROJECT_ID }}
          STORYBOOK_DEPLOYER_API_KEY: \${{ secrets.SCRY_API_KEY }}
`;
}

/**
 * Generate PR preview workflow
 */
function generatePRWorkflow(projectId, apiUrl, packageManager, buildCmd) {
    const pmSetup = getPackageManagerSetup(packageManager);
    const installCmd = getInstallCommand(packageManager);
    const cache = getCacheValue(packageManager);
    const runCmd = packageManager === 'npm' ? `npm run ${buildCmd}` : `${packageManager} run ${buildCmd}`;

    return `# Auto-generated by Scry Storybook Deployer
# Deploy Storybook preview for pull requests

name: Deploy Storybook PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

${pmSetup}      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
${cache}

      - name: Install dependencies
        run: ${installCmd}

      - name: Build Storybook
        run: ${runCmd}

      - name: Deploy Preview
        id: deploy
        run: |
          # Deploy with PR-specific version
          npx @scry/storybook-deployer \\
            --dir ./storybook-static \\
            --version pr-\${{ github.event.pull_request.number }}

          # Construct deployment URL
          PROJECT_ID="\${{ vars.SCRY_PROJECT_ID }}"
          API_URL="\${{ vars.SCRY_API_URL }}"
          DEPLOY_URL="\${API_URL}/\${PROJECT_ID}/pr-\${{ github.event.pull_request.number }}"
          echo "deployment_url=\$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          STORYBOOK_DEPLOYER_API_URL: \${{ vars.SCRY_API_URL }}
          STORYBOOK_DEPLOYER_PROJECT: \${{ vars.SCRY_PROJECT_ID }}
          STORYBOOK_DEPLOYER_API_KEY: \${{ secrets.SCRY_API_KEY }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = '\${{ steps.deploy.outputs.deployment_url }}';
            const prNumber = context.issue.number;
            const commitSha = context.payload.pull_request.head.sha.substring(0, 7);

            const commentBody = \`## 🚀 Storybook Preview Deployed

**Preview URL:** \${deploymentUrl}

📌 **Details:**
- **Commit:** \\\`\${commitSha}\\\`
- **Branch:** \\\`\${{ github.event.pull_request.head.ref }}\\\`
- **Deployed at:** \${new Date().toUTCString()}

> This preview updates automatically on each commit to this PR.\`;

            // Check if a comment from this bot already exists
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('🚀 Storybook Preview Deployed')
            );

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              });
              console.log('Updated existing PR comment');
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
              console.log('Created new PR comment');
            }
`;
}

module.exports = {
    generateMainWorkflow,
    generatePRWorkflow
};
