/**
 * Generate GitHub Actions workflow templates
 */

/**
 * Get package manager setup action
 */
function getPackageManagerSetup(packageManager) {
    switch (packageManager) {
        case 'pnpm':
            return `      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
`;
        case 'yarn':
            return ''; // Yarn is supported by default in setup-node
        case 'bun':
            return `      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
`;
        default:
            return '';
    }
}

/**
 * Get install command for package manager
 * All commands handle missing lockfiles gracefully
 */
function getInstallCommand(packageManager) {
    switch (packageManager) {
        case 'npm':
            // Use npm install which works with or without package-lock.json
            return 'npm install';
        case 'pnpm':
            // Just use pnpm install - it works with or without lockfile
            // We set CI=false to prevent pnpm from auto-enabling frozen-lockfile
            return 'CI=false pnpm install';
        case 'yarn':
            return 'yarn install';
        case 'bun':
            return 'bun install';
        default:
            return 'npm install';
    }
}

/**
 * Get cache value for package manager
 */
function getCacheValue(packageManager) {
    if (packageManager === 'npm') {
        return '';
    }
    return `          cache: '${packageManager}'`;
}

/**
 * Generate main deployment workflow
 */
/**
 * The command that fetches and runs a package that is not a project dependency.
 *
 * `npx` cannot be assumed. In a pnpm workflow it resolves against the
 * pnpm-managed environment and reports "playwright: not found" — exit 127 —
 * even with --yes. Each package manager has its own equivalent, so use it.
 */
function getDlxCommand(packageManager) {
    switch (packageManager) {
        case 'pnpm': return 'pnpm dlx';
        case 'yarn': return 'yarn dlx';
        default: return 'npx --yes';
    }
}

function generateMainWorkflow(projectId, apiUrl, packageManager, buildCmd) {
    const pmSetup = getPackageManagerSetup(packageManager);
    const installCmd = getInstallCommand(packageManager);
    const cache = getCacheValue(packageManager);
    const runCmd = packageManager === 'npm' ? `npm run ${buildCmd}` : `${packageManager} run ${buildCmd}`;
    const dlx = getDlxCommand(packageManager);

    return `# Auto-generated by Scry Storybook Deployer
# Deploy Storybook to production on push to main branch

name: Deploy Storybook

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for coverage new-code analysis
 
${pmSetup}      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
${cache}

      - name: Install dependencies
        run: ${installCmd}

      - name: Build Storybook
        run: ${runCmd}

      - name: Install Playwright browser
        # Screenshot capture drives --with-analysis, and without a browser every
        # story fails, no metadata archive is produced, and nothing is ever
        # indexed — while the deploy still exits 0 and the workflow goes green.
        # Chromium headless shell only: a few seconds, versus minutes for the
        # full browser set.
        # The version is left floating so it tracks sbcov's own playwright
        # ^1.41.0 optional dependency and installs a matching browser build.
        run: ${dlx} playwright install --with-deps chromium-headless-shell

      - name: Deploy to Scry
        run: |
          npx @scrymore/scry-deployer \\
            --dir ./storybook-static \\
            \${{ vars.SCRY_COVERAGE_ENABLED == 'false' && '--no-coverage' || '' }} \\
            \${{ vars.SCRY_COVERAGE_FAIL_ON_THRESHOLD == 'true' && '--coverage-fail-on-threshold' || '' }} \\
            \${{ vars.SCRY_COVERAGE_EXECUTE == 'false' && '' || '--coverage-execute' }} \\
            --with-analysis \\
            --coverage-base \${{ vars.SCRY_COVERAGE_BASE || github.event.before }}
        env:
          STORYBOOK_DEPLOYER_API_URL: \${{ vars.SCRY_API_URL }}
          STORYBOOK_DEPLOYER_PROJECT: \${{ vars.SCRY_PROJECT_ID }}
          STORYBOOK_DEPLOYER_API_KEY: \${{ secrets.SCRY_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;
}

/**
 * Generate PR preview workflow
 */
function generatePRWorkflow(projectId, apiUrl, packageManager, buildCmd) {
    const pmSetup = getPackageManagerSetup(packageManager);
    const installCmd = getInstallCommand(packageManager);
    const cache = getCacheValue(packageManager);
    const runCmd = packageManager === 'npm' ? `npm run ${buildCmd}` : `${packageManager} run ${buildCmd}`;
    const dlx = getDlxCommand(packageManager);

    return `# Auto-generated by Scry Storybook Deployer
# Deploy Storybook preview for pull requests

name: Deploy Storybook PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for coverage new-code analysis
 
${pmSetup}      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
${cache}

      - name: Install dependencies
        run: ${installCmd}

      - name: Build Storybook
        run: ${runCmd}

      - name: Install Playwright browser
        # Screenshot capture drives --with-analysis, and without a browser every
        # story fails, no metadata archive is produced, and nothing is ever
        # indexed — while the deploy still exits 0 and the workflow goes green.
        # Chromium headless shell only: a few seconds, versus minutes for the
        # full browser set.
        # The version is left floating so it tracks sbcov's own playwright
        # ^1.41.0 optional dependency and installs a matching browser build.
        run: ${dlx} playwright install --with-deps chromium-headless-shell

      - name: Deploy Preview
        id: deploy
        run: |
          # Deploy with PR-specific version
          npx @scrymore/scry-deployer \\
            --dir ./storybook-static \\
            --version pr-\${{ github.event.pull_request.number }} \\
            \${{ github.event.pull_request.draft == true && '--no-coverage' || '' }} \\
            \${{ vars.SCRY_COVERAGE_ENABLED == 'false' && '--no-coverage' || '' }} \\
            \${{ vars.SCRY_COVERAGE_FAIL_ON_THRESHOLD == 'true' && '--coverage-fail-on-threshold' || '' }} \\
            \${{ vars.SCRY_COVERAGE_EXECUTE == 'false' && '' || '--coverage-execute' }} \\
            --with-analysis \\
            --coverage-base \${{ vars.SCRY_COVERAGE_BASE || format('origin/{0}', github.base_ref) }}
 
          # Construct deployment URL using VIEW_URL (where users access the deployed Storybook)
          # Defaults to https://view.scrymore.com if SCRY_VIEW_URL is not set
          PROJECT_ID="\${{ vars.SCRY_PROJECT_ID }}"
          VIEW_URL="\${{ vars.SCRY_VIEW_URL || 'https://view.scrymore.com' }}"
          DEPLOY_URL="\${VIEW_URL}/\${PROJECT_ID}/pr-\${{ github.event.pull_request.number }}/"
          echo "deployment_url=\$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          STORYBOOK_DEPLOYER_API_URL: \${{ vars.SCRY_API_URL }}
          STORYBOOK_DEPLOYER_PROJECT: \${{ vars.SCRY_PROJECT_ID }}
          STORYBOOK_DEPLOYER_API_KEY: \${{ secrets.SCRY_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
`;
}

module.exports = {
    generateMainWorkflow,
    generatePRWorkflow
};
